### PR TITLE
Private events - Associations project 

### PR DESCRIPTION
**Pull request by ozovalihasan**
Please review code for ruby on rails private events project. In this project we:-

Set up a new rails app private events
Created User, Event, Invitation models and controller
Added 'attended_event' and 'attendee' associations by using Invitation model 
Created forms to sign up and create events
Created corresponding views
Added tests for model and features of the app
Finally used Miligram to style the project
Please review and give feedback which will be highly appreciated

Hasan and Hillary

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, but there are a few more things required. 
### General
### EventsController
- [x] index action
- lists past events, i.e. @past_events = Event.previous_events (screenshot from Odin)
- lists ucomping events, i.e. @upcoming_events = Event.upcoming_events 
* [x] the events table has column `creator_id` of type `integer`
* [x] an index for `creator_id` column is added
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by ozovalihasan** [comment]
Thank you @kobiyoyo for your feedback. We did the necessary changes.

**Review by rOluochKe — APPROVED** [review]
### Good job team, you got it right this time :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next project.
- Happy coding!

**Comment by ozovalihasan** [comment]
Thanks, @rOluochKe, for your feedback.

**Pull request merged**
